[package]
name = "poc_event_listener"
version = "0.1.0"
edition = "2021"

[dependencies.crossterm]
version = "0.27"
features = ["event-stream"]

[[bin]]
name = "event-read"
path = "src/examples/event-read.rs"
