/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Handler */

#ifndef _Included_Handler
#define _Included_Handler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Handler
 * Method:    notifyEvent
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Handler_notifyEvent
  (JNIEnv *, jclass);

/*
 * Class:     Handler
 * Method:    attentiveToNotify
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Handler_attentiveToNotify
  (JNIEnv *, jclass);

/*
 * Class:     Handler
 * Method:    helloFromRust
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Handler_helloFromRust
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
