[package]
name = "console"
version = "0.1.0"
edition = "2021"

[dependencies]
jni = "0.21.1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
dotenv = "0.15.0"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "client"
path = "src/bin/client.rs"