/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_shape_Shape */

#ifndef _Included_jni_shape_Shape
#define _Included_jni_shape_Shape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_shape_Shape
 * Method:    calculateCircleArea
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_jni_1shape_Shape_calculateCircleArea
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jni_shape_Shape
 * Method:    calculateCirclePerimeter
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_jni_1shape_Shape_calculateCirclePerimeter
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jni_shape_Shape
 * Method:    calculateArea
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_jni_1shape_Shape_calculateArea
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jni_shape_Shape
 * Method:    calculatePerimeter
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_jni_1shape_Shape_calculatePerimeter
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jni_shape_Shape
 * Method:    calculateArea1
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_jni_1shape_Shape_calculateArea1
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     jni_shape_Shape
 * Method:    calculatePerimeter1
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_jni_1shape_Shape_calculatePerimeter1
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     jni_shape_Shape
 * Method:    calculateArea2
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_jni_1shape_Shape_calculateArea2
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     jni_shape_Shape
 * Method:    calculatePerimeter2
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_jni_1shape_Shape_calculatePerimeter2
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
